/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModeldataUiModule extends AbstractModeldataUiModule {

	public ModeldataUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
