package MindMap.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CentralTopic = 0;
  public static final int MainTopic = 1;
  public static final int Marker = 2;
  public static final int MindMap = 3;
  public static final int SubTopic = 4;
  public static final int Topic = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x414cc6567c6848acL, 0x8c1095d6f5574ceaL);
    builder.put(0x45da3d247e17089cL, CentralTopic);
    builder.put(0x45da3d247e17089fL, MainTopic);
    builder.put(0x45da3d247e170894L, Marker);
    builder.put(0x45da3d247e170874L, MindMap);
    builder.put(0x45da3d247e1708a4L, SubTopic);
    builder.put(0x45da3d247e170877L, Topic);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
