/**
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.modeldata.impl;

import cl.ufro.dsl.modeldata.DataType;
import cl.ufro.dsl.modeldata.ModeldataPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModeldataPackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
