/**
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.modeldata;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cl.ufro.dsl.modeldata.ModeldataPackage#getAbstractElement()
 * @model
 * @generated
 */
public interface AbstractElement extends EObject
{
} // AbstractElement
