/**
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.modeldata;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cl.ufro.dsl.modeldata.ModeldataPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
