/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractModeldataValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(cl.ufro.dsl.modeldata.ModeldataPackage.eINSTANCE);
		return result;
	}
}
