/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.tests


import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import static org.junit.Assert.assertSame
import cl.ufro.dsl.modeldata.Entity
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import cl.ufro.dsl.modeldata.ModeldataPackage
import cl.ufro.dsl.validation.ModeldataValidator
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import cl.ufro.dsl.modeldata.Domainmodel

@ExtendWith(InjectionExtension)
@InjectWith(ModeldataInjectorProvider)
class ModeldataParsingTest {
	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	@Inject ValidationTestHelper validationTestHelper
	
	 @Inject extension CompilationTestHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test 
     def void parseDomainmodel() {
         val model = parseHelper.parse(
             "entity MyEntity {
                 parent: MyEntity
             }")
         val entity = model.elements.head as Entity
         assertSame(entity, entity.features.head.type)
     }
     
      @Test
 def testValidModel() {
     val entity = parseHelper.parse(
         "entity MyEntity {
             parent: MyEntity
         }")
     validationTestHelper.assertNoIssues(entity)
 } 
 
  @Test
 def testNameStartsWithCapitalWarning() {
     val entity = parseHelper.parse(
         "entity myEntity {
             parent: myEntity
         }")
     validationTestHelper.assertWarning(entity,
         ModeldataPackage.Literals.ENTITY,
         ModeldataValidator.INVALID_NAME,
         "Name should start with a capital"
     )
 }
 
 @Test def test() {
     '''
         datatype String

         package my.company.blog {
             entity Blog {
                 title: String
             }
         }
     '''.assertCompilesTo('''
         package my.company.blog;

         public class Blog {
            private String title;
         	 
             public String getTitle() {
                 return title;
             }
             
             public void setTitle(String title) {
                 this.title = title;
             }
         }
     ''')
     }
}
