/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModeldataRuntimeModule extends AbstractModeldataRuntimeModule {
}
