/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModeldataStandaloneSetup extends ModeldataStandaloneSetupGenerated {

	public static void doSetup() {
		new ModeldataStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
