/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModeldataAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cl/ufro/dsl/parser/antlr/internal/InternalModeldata.tokens");
	}
}
