/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.parser.antlr;

import cl.ufro.dsl.parser.antlr.internal.InternalModeldataParser;
import cl.ufro.dsl.services.ModeldataGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ModeldataParser extends AbstractAntlrParser {

	@Inject
	private ModeldataGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModeldataParser createParser(XtextTokenStream stream) {
		return new InternalModeldataParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public ModeldataGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModeldataGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
