/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModeldataScopeProvider extends DelegatingScopeProvider {
}
