/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.ide;

import cl.ufro.dsl.ModeldataRuntimeModule;
import cl.ufro.dsl.ModeldataStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ModeldataIdeSetup extends ModeldataStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModeldataRuntimeModule(), new ModeldataIdeModule()));
	}
	
}
