/**
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.tests;

import cl.ufro.dsl.modeldata.AbstractElement;
import cl.ufro.dsl.modeldata.Domainmodel;
import cl.ufro.dsl.modeldata.Entity;
import cl.ufro.dsl.modeldata.Feature;
import cl.ufro.dsl.modeldata.ModeldataPackage;
import cl.ufro.dsl.tests.ModeldataInjectorProvider;
import cl.ufro.dsl.validation.ModeldataValidator;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.testing.CompilationTestHelper;
import org.junit.Assert;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(ModeldataInjectorProvider.class)
@SuppressWarnings("all")
public class ModeldataParsingTest {
  @Inject
  private ParseHelper<Domainmodel> parseHelper;
  
  @Inject
  private ValidationTestHelper validationTestHelper;
  
  @Inject
  @Extension
  private CompilationTestHelper _compilationTestHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void parseDomainmodel() {
    try {
      final Domainmodel model = this.parseHelper.parse(
        "entity MyEntity {\r\n                 parent: MyEntity\r\n             }");
      AbstractElement _head = IterableExtensions.<AbstractElement>head(model.getElements());
      final Entity entity = ((Entity) _head);
      Assert.assertSame(entity, IterableExtensions.<Feature>head(entity.getFeatures()).getType());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testValidModel() {
    try {
      final Domainmodel entity = this.parseHelper.parse(
        "entity MyEntity {\r\n             parent: MyEntity\r\n         }");
      this.validationTestHelper.assertNoIssues(entity);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testNameStartsWithCapitalWarning() {
    try {
      final Domainmodel entity = this.parseHelper.parse(
        "entity myEntity {\r\n             parent: myEntity\r\n         }");
      this.validationTestHelper.assertWarning(entity, 
        ModeldataPackage.Literals.ENTITY, 
        ModeldataValidator.INVALID_NAME, 
        "Name should start with a capital");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void test() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("datatype String");
      _builder.newLine();
      _builder.newLine();
      _builder.append("package my.company.blog {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("entity Blog {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("title: String");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("package my.company.blog;");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("public class Blog {");
      _builder_1.newLine();
      _builder_1.append("   ");
      _builder_1.append("private String title;");
      _builder_1.newLine();
      _builder_1.append("\t ");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("public String getTitle() {");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("return title;");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("public void setTitle(String title) {");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("this.title = title;");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      this._compilationTestHelper.assertCompilesTo(_builder, _builder_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
