/*
 * generated by Xtext 2.24.0-SNAPSHOT
 */
package cl.ufro.dsl.ui.tests;

import cl.ufro.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ModeldataUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("cl.ufro.dsl.Modeldata");
	}

}
