package MindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CentralTopic_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.mainTopics$jrHt)) {
      tgs.appendNode(item);
    }
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink mainTopics$jrHt = MetaAdapterFactory.getContainmentLink(0x414cc6567c6848acL, 0x8c1095d6f5574ceaL, 0x45da3d247e17089cL, 0x45da3d247e1708a2L, "mainTopics");
  }
}
