package MindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class MindMap_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("\\documentclass{article}");
    tgs.newLine();
    tgs.append("\\begin{document}");
    tgs.newLine();
    tgs.append("\\title{");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.centralTopic$I07U), PROPS.name$MnvL));
    tgs.append("}");
    tgs.newLine();
    tgs.append("\\autor{");
    tgs.append("}");
    tgs.newLine();
    tgs.append("\\maketitle");
    tgs.newLine();
    tgs.append("\\begin{abstract}");
    tgs.newLine();
    tgs.append("\\end{abstract}");
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.centralTopic$I07U));
    tgs.newLine();

    tgs.append("\\end{document}");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink centralTopic$I07U = MetaAdapterFactory.getContainmentLink(0x414cc6567c6848acL, 0x8c1095d6f5574ceaL, 0x45da3d247e170874L, 0x45da3d247e1a95baL, "centralTopic");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
