package MindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import MindMap.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.CentralTopic:
        return new CentralTopic_TextGen();
      case LanguageConceptSwitch.MainTopic:
        return new MainTopic_TextGen();
      case LanguageConceptSwitch.MindMap:
        return new MindMap_TextGen();
      case LanguageConceptSwitch.SubTopic:
        return new SubTopic_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.MindMap$BK)) {
        String fname = getFileName_MindMap(root);
        String ext = getFileExtension_MindMap(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_MindMap(SNode node) {
    return "mindmap_" + SPropertyOperations.getString(node, PROPS.name$MnvL);
  }
  private static String getFileExtension_MindMap(SNode node) {
    return "tex";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MindMap$BK = MetaAdapterFactory.getConcept(0x414cc6567c6848acL, 0x8c1095d6f5574ceaL, 0x45da3d247e170874L, "MindMap.structure.MindMap");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
